### ISSUE TITLE
Interpreting rack-timeout log

### ISSUE THREAD

**Issue by janklimo** [heroku/rack-timeout#135]
Hey guys,

my apologies, as this is not an issue with `rack-timeout` per se, rather an attempt to understand its log output. While not a direct problem with the gem, I think it may benefit other users with similar problem in the future.

In a Rails app I'm using `rack-timeout` set to time out requests taking longer than 30 seconds.

Strangely, there are situations where `rack-timeout` enters extremely late and the overall service time of the request can end up being up to 30 minutes.

Here is an example to illustrate this situation:

![paths](https://user-images.githubusercontent.com/7811733/41281884-c0516c2c-6e5c-11e8-846c-59a246b16e8e.png)

What I find hard to explain is why the first log from `rack-timeot` (`state=ready`) comes such a long time after H12 from Heroku. This states that the wait time was ~30s while service time was ~27 minutes. Wouldn't wait time have to be ~27 minutes for these numbers to add up?

Here's my middleware stack:

```ruby
use Raven::Rack
use HireFire::Middleware
use ActionDispatch::SSL
use Rack::Sendfile
use HeaderDelete
use ActionDispatch::Static
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x0000000002d643e8>
use Rack::Timeout
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use LoggingMiddleware
use Rails::Rack::Logger
use Chewy::Railtie::RequestStrategy
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
...
```

We're using NewRelic. I suspect it may be interfering since it uses `Mutex#synchronize` internally? Could IO blocks cause this?

Thank you for any ideas!

**Comment by wuputah** [comment]
I agree the behavior is weird - I'd expect `ready` to be printed (very much) sooner, since it proceeded to `active` with 52ms left on the clock. While it's unlikely, it is possible that something would block Rack::Timeout between initialization (when it calculates the timeout values) and when it logs this message. 

Since the time you're seeing there is the time received by Papertrail, there's another chance that there was some logging buffering happened - that the message was printed but not flushed and sent through the logging system. 

A possible solution is Rack::Timeout could log and print its own timestamp, but in most cases that would just be noise and duplication.

**Comment by wuputah** [comment]
The most relevant info here is in [doc/risks.md](https://github.com/heroku/rack-timeout/blob/master/doc/risks.md) - hope that helps.
