### ISSUE TITLE
Has anyone else seen timeout errors long after the set threshold?

### ISSUE THREAD

**Issue by ryantownsend** [heroku/rack-timeout#139]
I'm investigating some weird memory leaks in a Rails application that seem to correlate with a timeout error on random routes – these errors are logged with the transaction having taken millions of milliseconds (10 - 20 hours in total!)

Just curious whether anyone else has experienced this or could help point me to what could possibly be wrong. NewRelic has no further detail about the request and given it's not specific to a given controller/action, it's hard to understand what could be going wrong here.

Could this be something in the scheduler?

![screen shot 2018-08-08](https://user-images.githubusercontent.com/12299/43864035-733ae19e-9b56-11e8-89b4-85d613109c17.png)

**Comment by wuputah** [comment]
Requests that are timed out may not report data to tools like New Relic correctly, since their reporting may be interrupted. I suspect (and hope?) that this data is not accurate. You can see that "timestamp" doesn't seem to indicate that the request took more than 67 seconds? So I think because the request didn't finish, you're not getting an "end time" for the request.

This will also be specific to what version of Timeout and New Relic you are using. New Relic has gotten quite complex as well so not sure how it works these days.

These "long" requests may also be holding data in New Relic, and that could be where your memory leak is coming from. It's even possible that this is causing Ruby to hold onto data that was used during that request if the request object hasn't gone out of scope.

**Comment by ryantownsend** [comment]
Thanks @wuputah, I'll have the gem bundle updated and see if that improves the situation. I'll close this ticket for now and respond back in future if it continues.
