### ISSUE TITLE
Silence rack-timeout logs except errors

### ISSUE THREAD

**Issue by izoomi** [heroku/rack-timeout#63]
I noticed there's a lot of this in the log:

    source=rack-timeout id=874bf8 timeout=29000ms state=ready
    source=rack-timeout id=874bf8 timeout=29000ms service=0ms state=active
    source=rack-timeout id=874bf8 timeout=29000ms service=1ms state=completed
    source=rack-timeout id=3bbc38 timeout=29000ms state=ready
    source=rack-timeout id=3bbc38 timeout=29000ms service=0ms state=active
    source=rack-timeout id=3bbc38 timeout=29000ms service=1ms state=completed

Is there a way to silence rack-timeout, except errors, without changing my log level and affecting other log data?

**Comment by kch** [comment]
You can instantiate a separate logger for rack timeout with a different level. 

This ended up being somewhat convoluted, I should probably make it easier, but here goes:

```ruby
Rack::Timeout::StageChangeLoggingObserver.logger = \
Rack::Timeout::StageChangeLoggingObserver.mk_logger($stderr, ::Logger::INFO)
```

This example outputs to `$stderr`, but obviously you can set any IO target you want.

**Comment by izoomi** [comment]
Ah ok, that works. Thanks! :+1:

**Comment by andrew2005** [comment]
For future reference, there is now a [convenience method] (https://github.com/heroku/rack-timeout/commit/674cbdf54c4346be4a486a7e139bebdb35b866e2) to clean this up a bit. Put this in your initializer instead:

    Rack::Timeout::Logger.update($stderr, ::Logger::ERROR)

If you still want to use the above format, note the recent spelling change to `StateChange` rather than `StageChange`.
