### ISSUE TITLE
ThreadError: Attempt to unlock a mutex which is locked by another thread

### ISSUE THREAD

**Issue by kch** [heroku/rack-timeout#65]
Spin off from #55 

cc @abevoelker, @vasilakisfil, @seanknox 

These errors might be worth looking into separately from the capybara issue. Were you all using capybara?

Please list your your server, framework, versions, dependencies here. A full trace on that ThreadError would be great too if you can capture one.

**Comment by seanknox** [comment]
Possibly relevant while debugging [#55](https://github.com/heroku/rack-timeout/issues/55#issuecomment-75450863). Rails 4.2.0 app using turbolinks and sprinkling of backbone.js, rack-timeout v0.1.0, capybara/selenium, postgres. Very light client-side/JS code. It's almost entirely pure Rails.

Running our test suite, encountered the locked mutex error in a integration spec with Capybara and Puma as Capybara's rack server:

```
Failure/Error: Unable to find matching line from backtrace
     ThreadError:
       Attempt to unlock a mutex which is locked by another thread
     # /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/lock.rb:22:in `unlock'
     # /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/lock.rb:22:in `ensure in call'
     # /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/lock.rb:23:in `call'
     # /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/static.rb:113:in `call'
     # /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/sendfile.rb:113:in `call'
     # /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/rack-timeout-0.2.0/lib/rack/timeout.rb:108:in `call'
     # /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call'
     # /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:164:in `call'
     # /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/urlmap.rb:66:in `block in call'
     # /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `each'
     # /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `call'
     # /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/capybara-2.4.4/lib/capybara/server.rb:19:in `call'
     # /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/puma-2.11.0/lib/puma/server.rb:507:in `handle_request'
     # /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/puma-2.11.0/lib/puma/server.rb:375:in `process_client'
     # /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/puma-2.11.0/lib/puma/server.rb:262:in `block in run'
     # /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:104:in `call'
     # /opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

**Comment by jaybbb** [comment]
I have the same error since I switched from Unicorn to Puma, if I can help debugging please let me know what do you need,

Thanks,

**Comment by dkubb** [comment]
@jaybbb I think I may have fixed the bug in Rack::Lock that was triggering this.

If you (or anyone else) wants to help debug this, feel free to add this to your Gemfile:

```ruby
# If you are using Rack 1.5.2
gem 'rack', '~> 1.5.2', git: 'https://github.com/dkubb/rack.git', branch: 'fix/rack-1.5/rack-lock-mutex-usage'

# If you are using Rack 1.6.0
gem 'rack', '~> 1.6.0', git: 'https://github.com/dkubb/rack.git', branch: 'fix/1-6-stable/rack-lock-mutex-usage'
```

I've been testing this out in a $work app and so far it's been good. If it runs for a while with no issues I'll submit PRs upstream to fix the `rack-1.5` and `1-6-stable` branches.

**Comment by seanknox** [comment]
@dkubb those fixes look legit. Great find and hope to see these in a PR soon. 

Out of curiosity, how'd you find the issue in rack? Just followed the stack trace?

**Comment by dkubb** [comment]
@seanknox Most of the stack traces I saw here and on my own showed errors raised in and around `Rack::Lock`. I also saw some people experimenting with moving it around the middleware stack to (attempt to) avoid issues. Once I started digging in I realized that when the system was getting bogged down is when this problem occurred. I assumed what was happening is that a bunch of threads would be sitting waiting for that initial `@mutex.lock` and then would be timed out. When the timeout happens, the `@mutex.unlock` in the ensure was being executed but because the thread hadn't yet acquire ownership over the mutex we were seeing all these `ThreadError` exceptions being thrown. Once I moved the begin block *after* the `@mutex` lock the bulk of the issues went away.

After fixing it I started auditing the rest of the code and refactoring and found a couple more issues which I outlined in the PR I just submitted upstream:

https://github.com/rack/rack/pull/828

**Comment by seanknox** [comment]
@dkubb excellent! as I mentioned on the rack PR, I've been running our test suite with rack-timeout and your branch of 1.6.0 for hours and can't trigger a hang. Looking good.

**Comment by kch** [comment]
@dkubb great job tracking this down. Let's hope it gets merged and released quickly.

**Comment by seanknox** [comment]
So bad news: With the fix in place, running `rspec` directly never seems to hang. Running rspec through `thor`, does. Not sure what's so different about running rspec through thor.

**Comment by dkubb** [comment]
@seanknox hmm, I'm not too familiar with thor these days. I played with it a while ago when it came out but I tend to use rake for small command line utilities.

What kinds of tests are you running? What web server are you using? Are you running the tests in a loop via shell? (so you're tearing down a process after each run, or maybe you're running this all in a process that never terminates)

One thing I've seen locally is what I can only describe as a kind of thread pool exhaustion, I think. I don't know how puma works internally (yet) but I think it spins up a pool of 16 threads when I run "rails server". Over time as threads are killed by rack-timeout it's almost like they aren't getting replaced because after a while I can't really do anything.

It could very well be something exposed by my change that was waiting there all along. It could be caused by the change too. At this point the best thing is to get as many people testing the patch to see if their problems are fixed or if they see what I am seeing or something else entirely.

**Comment by seanknox** [comment]
@dkubb We're running RSpec feature/integration tests with Capybara. Rails 4.2.x app using Turbolinks and sprinkling of backbone.js, rack-timeout v0.2.0, capybara/selenium (Chrome), postgres. Very light client-side/JS code. It's almost entirely pure Rails. We are using puma on Heroku, but in tests it's Thin.

I ran our test suite overnight with both RSpec and through `thor`—both hung eventually.

**Comment by dkubb** [comment]
> I ran our test suite overnight with both RSpec and through thor—both hung eventually.

Damn, it'll be hard to know if my patch is responsible for this or if it fixed the specific `Rack::Lock` bug and just exposed a different bug in another place.

I hope the rack people audit it and merge it if they think it's an improvement, or offer suggestions on how I can improve it.

@seanknox are you able to trace where things are hanging? Using ruby's `Tracer` or other gems it should be possible to log the execution of the code and infer where it is hanging by which statements are executed last in the logs before everything hangs. Until it's narrowed down the entire surface area of the application and dependencies is suspect and I don't think it would be possible to debug.

**Comment by kch** [comment]
> One thing I've seen locally is what I can only describe as a kind of thread pool exhaustion.

Wonder if doing #61 would help.

> At this point the best thing is to get as many people testing the patch to see if their problems are fixed or if they see what I am seeing or something else entirely.

I did ask for that in #55.

--

@seanknox what @dkubb said, looking at the trace for the hangs will help. Might be another lock thing. 

This boils down the problem mentioned in the README that rack-timeout is inherently unsafe. It'll abort at places that leaves things corrupted. `Thread#handle_interrupt` can be used to prevent this, but it has to be added in every place where there could be a problem…

Honestly, the way I use rack-timeout and the way I try to insist that people should is as a debug tool. I find places where rack-timeout had to abort, and then I use the relevant library's own timeout mechanism, which is expected to be safe. Most common cases are http connections and database connections and queries. But basically, anything that does IO should be treated as a danger zone.

**Comment by kch** [comment]
Also, is `Rack::Lock` even necessary? A mutex around every entire request seems to miss the point of threading.

**Comment by kch** [comment]
@seanknox @dkubb wondering if calling `unlock` only if `owned?` would help wit the remaining hangs.

**Comment by dkubb** [comment]
> Also, is Rack::Lock even necessary? A mutex around every entire request seems to miss the point of threading.

@kch I think it's mainly used to make rails' dynamic constant reloading work. `Rack::Lock` appears after the static middleware handlers, so the requests to rails controllers will be serialized but assets can still be fetched in parallel.

**Comment by dkubb** [comment]
>  wondering if calling unlock only if owned? would help with the remaining hangs.

I thought about that, but I couldn't think of any reason that the unlock code could be reached without it owning the mutex. It's still still worth a try, even if just to rule it out.

**Comment by dkubb** [comment]
> Wonder if doing #61 would help.

@kch so the idea is a single thread just continuously loops and checks all the registered timeouts for all the other threads, raising an error if the thread is still alive after the timeout? That seems like a good solution. I can't say if it'll solve this specific problem but it seems more efficient than a 1:1 mapping.

The real question I would probably have is, will it result in code that is simpler to understand? If it results in code that has less moving parts or less state to manage, or even just code that is easier to reason about, then I would support it. Not saying the existing code is too complex, but it seems like a step in the right direction if it simplifies things even if it doesn't resolve the exact problem.

**Comment by simon-engledew** [comment]
Just some more observations:

When testing with Puma, I have seen it close the body *and* return a response when using puma rack timeout. This results in the mutex being unlocked twice by Rack::Lock then throwing a ThreadError.

Here is the snippet I believe is responsible in Puma server.rb:

```
      ensure
        uncork_socket client

        body.close
        req.tempfile.unlink if req.tempfile
        res_body.close if res_body.respond_to? :close

        after_reply.each { |o| o.call }
      end
```

I've managed to handle this misbehaviour by making a small patch to rack lock:

latest: https://github.com/simon-engledew/rack/tree/patch-1
1.4.7: https://github.com/simon-engledew/rack/tree/patch-2

This absolutely ensures the mutex will only ever be unlocked once by a thread. With this, puma as the server and database cleaner instead of transactions our test suite runs flawlessly! Huzzah.

**Comment by kch** [comment]
While we wait for https://github.com/rack/rack/pull/828 to make its way into a release, the commits at the [rails-middleware-order](https://github.com/heroku/rack-timeout/tree/rails-middleware-order) tag change the way the `Rack::Timeout` middleware is inserted, so that it should end up after `Rack::Lock`.

This will make its way into the next beta, but for the moment just source from that tag.

**Comment by kch** [comment]
Betas will be announced in #78. Closing.
