### ISSUE TITLE
take timeout settings as options to the middleware's constructor

### ISSUE THREAD

**Issue by kch** [heroku/rack-timeout#72]
per https://github.com/interagent/pliny/pull/142#discussion_r27527306

cc @brandur

**Comment by brandur** [comment]
+1! Thanks.

**Comment by kch** [comment]
@brandur can you remind me why this was a good idea?

Your original comment:

> you should consider taking options into the middleware's constructor! That would allow for varying timeout depending on the middleware stack that you're building (compared to a global option).

**Comment by brandur** [comment]
> @brandur can you remind me why this was a good idea?

@kch I guess that broadly there are two reasons:

1. Favoring injection over global variables is generally a good idea because you can configure multiple instances independently. If the same app has multiple Rack stacks, you could configure different timeout middlewares with two different timeout values without resorting to any tricks.
2. Using constructor options is the standard way of configuring Rack middleware. This convention may sound relatively unimportant, but it's nice being able to look at a configured stack and see exactly which options are going into each module all in one place.

**Comment by kch** [comment]
How would such config happen in the most common context which is rails apps?

**Comment by brandur** [comment]
@kch See [configuring middleware stack in the Rails documentation](http://guides.rubyonrails.org/rails_on_rack.html#configuring-middleware-stack) for details (specifically look at the method signatures).

It looks roughly like this:

```
config.middleware.use Rack::Timeout, timeout: 30
```
